-- Frontend Asoslari
INSERT INTO public.quizzes (id, title, subject_id, level) VALUES
  ('11111111-1111-1111-1111-111111111111', 'Frontend Asoslari (React & UI)', 'frontend', 'O''rta')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.questions (quiz_id, text, options, correct_option, explanation, order_num) VALUES
('11111111-1111-1111-1111-111111111111', 'React''da state nima?', '[{"id": "a", "text": "Komponentning ichki xotirasi"}, {"id": "b", "text": "Tashqi API"}, {"id": "c", "text": "CSS klass"}, {"id": "d", "text": "Ma''lumotlar bazasi"}]', 'a', 'State bu komponentning o''zgaruvchan ma''lumotlarini saqlovchi obyekt.', 1),
('11111111-1111-1111-1111-111111111111', 'Virtual DOM nima?', '[{"id": "a", "text": "Haqiqiy DOMning ko''chirmasi"}, {"id": "b", "text": "Brauzer oynasi"}, {"id": "c", "text": "CSS fayli"}, {"id": "d", "text": "Server arxitekturasi"}]', 'a', 'Virtual DOM bu haqiqiy DOM ning xotiradagi nusxasi bo''lib, ishlash tezligini oshiradi.', 2),
('11111111-1111-1111-1111-111111111111', 'useEffect hooki qachon ishga tushadi?', '[{"id": "a", "text": "Renderdan keyin"}, {"id": "b", "text": "Faqat birinchi marta"}, {"id": "c", "text": "Tugma bosilganda"}, {"id": "d", "text": "Xatolik berganda"}]', 'a', 'useEffect odatda har bir render tugagach ishga tushadi (qaramliklarga qarab).', 3),
('11111111-1111-1111-1111-111111111111', 'Props nima uchun ishlatiladi?', '[{"id": "a", "text": "Komponentlararo ma''lumot uzatish"}, {"id": "b", "text": "Serverga ulanish"}, {"id": "c", "text": "CSS yozish"}, {"id": "d", "text": "Ma''lumotni saqlash"}]', 'a', 'Props ota komponentdan bola komponentga ma''lumot o''tkazish uchun ishlatiladi.', 4),
('11111111-1111-1111-1111-111111111111', 'CSS Flexbox''da elementlarni o''rtaga joylash qaysi qoida bilan qilinadi?', '[{"id": "a", "text": "justify-content: center; align-items: center;"}, {"id": "b", "text": "text-align: center;"}, {"id": "c", "text": "float: center;"}, {"id": "d", "text": "margin: auto;"}]', 'a', 'Flexbox da gorizontal va vertikal o''rtaga joylash uchun shu qoidalar ishlatiladi.', 5),
('11111111-1111-1111-1111-111111111111', 'React Router vazifasi nima?', '[{"id": "a", "text": "Sahifalararo o''tishni ta''minlash"}, {"id": "b", "text": "Fayllarni yuklash"}, {"id": "c", "text": "Dizayn qilish"}, {"id": "d", "text": "API yaratish"}]', 'a', 'React Router SPA (Single Page Application) larda sahifalarni boshqaradi.', 6),
('11111111-1111-1111-1111-111111111111', 'Tailwind CSS ning asosiy yutug''i nima?', '[{"id": "a", "text": "Utility-first yondashuv"}, {"id": "b", "text": "Sekin ishlashi"}, {"id": "c", "text": "JS yozish shart emasligi"}, {"id": "d", "text": "Faqat React uchunligi"}]', 'a', 'Tailwind HTML klasslari orqali tezkor stil berish (utility-first) imkonini beradi.', 7),
('11111111-1111-1111-1111-111111111111', 'HTML da <a> tegining vazifasi?', '[{"id": "a", "text": "Havola (link) yaratish"}, {"id": "b", "text": "Rasm qo''yish"}, {"id": "c", "text": "Matnni qalin qilish"}, {"id": "d", "text": "Sarlavha"}]', 'a', 'Anchor tag (<a>) boshqa sahifalarga o''tish uchun ishlatiladi.', 8),
('11111111-1111-1111-1111-111111111111', 'Babel qanday vazifani bajaradi?', '[{"id": "a", "text": "Yangi JS kodni eski brauzerlarga moslash"}, {"id": "b", "text": "Kodni formatlash"}, {"id": "c", "text": "Xatolarni qidirish"}, {"id": "d", "text": "Serverni ishga tushirish"}]', 'a', 'Babel zamonaviy ES6+ kodini hamma brauzerlar tushunadigan ES5 ga o''giradi.', 9),
('11111111-1111-1111-1111-111111111111', 'Redux nima maqsadda ishlatiladi?', '[{"id": "a", "text": "Global stateni boshqarish"}, {"id": "b", "text": "UI komponentlar yaratish"}, {"id": "c", "text": "API so''rovlar qilish"}, {"id": "d", "text": "Ma''lumotlar bazasi"}]', 'a', 'Redux butun dastur bo''ylab state (holat) ni yagona joyda saqlash imkonini beradi.', 10);

-- Backend
INSERT INTO public.quizzes (id, title, subject_id, level) VALUES
  ('22222222-2222-2222-2222-222222222222', 'Backend (Node.js & Ma''lumotlar Bazasi)', 'backend', 'Qiyin')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.questions (quiz_id, text, options, correct_option, explanation, order_num) VALUES
('22222222-2222-2222-2222-222222222222', 'Node.js bu nima?', '[{"id": "a", "text": "JS ni serverda ishlashiga imkon beruvchi muhit"}, {"id": "b", "text": "Yangi dasturlash tili"}, {"id": "c", "text": "Ma''lumotlar bazasi"}, {"id": "d", "text": "CSS framework"}]', 'a', 'Node.js V8 dvigateli asosida ishlovchi JavaScript ishchi muhitidir.', 1),
('22222222-2222-2222-2222-222222222222', 'Express.js nima uchun kerak?', '[{"id": "a", "text": "Server yaratishni osonlashtirish uchun"}, {"id": "b", "text": "Fayllarni o''qish uchun"}, {"id": "c", "text": "Ma''lumotlarni shifrlash"}, {"id": "d", "text": "Dizayn chizish"}]', 'a', 'Express Node.js uchun eng mashhur minimal veb freymvork hisoblanadi.', 2),
('22222222-2222-2222-2222-222222222222', 'API nima?', '[{"id": "a", "text": "Application Programming Interface"}, {"id": "b", "text": "Advanced Protocol Internet"}, {"id": "c", "text": "Apple Programming Interface"}, {"id": "d", "text": "Automated Process Integration"}]', 'a', 'API ikki tizim o''zaro gaplashishi uchun qoidalar to''plamidir.', 3),
('22222222-2222-2222-2222-222222222222', 'PostgreSQL qanday ma''lumotlar bazasi?', '[{"id": "a", "text": "Relyatsion (SQL)"}, {"id": "b", "text": "NoSQL"}, {"id": "c", "text": "Graf"}, {"id": "d", "text": "Fayl tizimi"}]', 'a', 'PostgreSQL kuchli ochiq kodli relyatsion (SQL) bazadir.', 4),
('22222222-2222-2222-2222-222222222222', 'JWT qanday maqsadlarda ishlatiladi?', '[{"id": "a", "text": "Foydalanuvchi autentifikatsiyasi uchun"}, {"id": "b", "text": "Video yuklash uchun"}, {"id": "c", "text": "Kodni testlash uchun"}, {"id": "d", "text": "Ma''lumotlarni bazaga yozish"}]', 'a', 'JSON Web Token (JWT) asosan autentifikatsiya va avtorizatsiyada ishlatiladi.', 5),
('22222222-2222-2222-2222-222222222222', 'Middleware nima?', '[{"id": "a", "text": "So''rov va javob o''rtasidagi funksiya"}, {"id": "b", "text": "Ma''lumotlar bazasi turi"}, {"id": "c", "text": "Frontend UI elementi"}, {"id": "d", "text": "OS yadrosi"}]', 'a', 'Express da middleware HTTP request va response obyektlari o''rtasida ishlovchi funksiyadir.', 6),
('22222222-2222-2222-2222-222222222222', 'REST API ning asosiy metodlari qaysilar?', '[{"id": "a", "text": "GET, POST, PUT, DELETE"}, {"id": "b", "text": "READ, WRITE, EXECUTE"}, {"id": "c", "text": "START, STOP, PAUSE"}, {"id": "d", "text": "PUSH, PULL, COMMIT"}]', 'a', 'Bular REST arxitekturasining asosiy CRUD amallarini bajaruvchi HTTP metodlaridir.', 7),
('22222222-2222-2222-2222-222222222222', 'NPM nima?', '[{"id": "a", "text": "Node Package Manager"}, {"id": "b", "text": "New Project Manager"}, {"id": "c", "text": "Node Program Maker"}, {"id": "d", "text": "Network Protocol Monitor"}]', 'a', 'Node.js uchun paketlarni (kutubxonalarni) boshqarish tizimi.', 8),
('22222222-2222-2222-2222-222222222222', 'Callback Hell (Callback Do''zaxi) nima?', '[{"id": "a", "text": "Ketma-ket ichma-ich yozilgan callbacklar"}, {"id": "b", "text": "Tizimning buzilishi"}, {"id": "c", "text": "Server xatosi"}, {"id": "d", "text": "Virus turi"}]', 'a', 'Asinxron operatsiyalarni callback orqali yozganda paydo bo''ladigan murakkab kod tuzilishi.', 9),
('22222222-2222-2222-2222-222222222222', 'SQL''da barcha ustunlarni tanlash uchun qaysi belgi ishlatiladi?', '[{"id": "a", "text": "*"}, {"id": "b", "text": "#"}, {"id": "c", "text": "%"}, {"id": "d", "text": "$"}]', 'a', 'SELECT * hamma ustunlarni bildiradi.', 10);

-- JavaScript Asoslari
INSERT INTO public.quizzes (id, title, subject_id, level) VALUES
  ('33333333-3333-3333-3333-333333333333', 'JavaScript Asoslari', 'javascript', 'Oson')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.questions (quiz_id, text, options, correct_option, explanation, order_num) VALUES
('33333333-3333-3333-3333-333333333333', 'JavaScript da o''zgaruvchi e''lon qilish uchun qaysi kalit so''zlardan foydalaniladi?', '[{"id": "a", "text": "var, let, const"}, {"id": "b", "text": "int, string, bool"}, {"id": "c", "text": "define, set, let"}, {"id": "d", "text": "variable, val, const"}]', 'a', 'ES6 da o''zgaruvchilar asosan let va const bilan, eskidan esa var bilan e''lon qilinadi.', 1),
('33333333-3333-3333-3333-333333333333', 'typeof operatori nima qaytaradi?', '[{"id": "a", "text": "Qiymatning ma''lumot turini"}, {"id": "b", "text": "O''zgaruvchi nomini"}, {"id": "c", "text": "Xatolikni"}, {"id": "d", "text": "Obyektni"}]', 'a', 'typeof qiymat string, number, object ekanligini bildiradi.', 2),
('33333333-3333-3333-3333-333333333333', 'Massivning oxiriga element qo''shish uchun qaysi metod ishlatiladi?', '[{"id": "a", "text": "push()"}, {"id": "b", "text": "pop()"}, {"id": "c", "text": "shift()"}, {"id": "d", "text": "unshift()"}]', 'a', 'push() massiv oxiriga yangi element qo''shadi.', 3),
('33333333-3333-3333-3333-333333333333', 'DOM so''zining kengaytmasi?', '[{"id": "a", "text": "Document Object Model"}, {"id": "b", "text": "Data Object Model"}, {"id": "c", "text": "Document Oriented Module"}, {"id": "d", "text": "Dynamic Output Method"}]', 'a', 'Veb sahifaning strukturasini ifodalovchi obyekt modeli.', 4),
('33333333-3333-3333-3333-333333333333', 'setTimeout qanday ishlaydi?', '[{"id": "a", "text": "Ma''lum vaqt o''tgach funksiyani bajaradi"}, {"id": "b", "text": "Dasturni to''xtatadi"}, {"id": "c", "text": "Har xil vaqtda qaytadan bajaradi"}, {"id": "d", "text": "Vaqtni o''lchaydi"}]', 'a', 'Belgilangan millisekunddan keyin bitta funksiyani bir marta ishga tushiradi.', 5),
('33333333-3333-3333-3333-333333333333', 'JSON.stringify() nima qiladi?', '[{"id": "a", "text": "Obyektni qatorga (stringga) aylantiradi"}, {"id": "b", "text": "Qatorni obyektga aylantiradi"}, {"id": "c", "text": "Massivni o''chiradi"}, {"id": "d", "text": "Tarmoqqa jo''natadi"}]', 'a', 'JS obyektini JSON formatidagi matnga o''tkazadi.', 6),
('33333333-3333-3333-3333-333333333333', 'Promise larning nechta holati bor?', '[{"id": "a", "text": "3 ta (Pending, Fulfilled, Rejected)"}, {"id": "b", "text": "2 ta (True, False)"}, {"id": "c", "text": "4 ta"}, {"id": "d", "text": "Cheksiz"}]', 'a', 'Promiselar kutilayotgan, bajarilgan yoki rad etilgan holatlarda bo''ladi.', 7),
('33333333-3333-3333-3333-333333333333', '=== va == o''rtasidagi farq?', '[{"id": "a", "text": "=== ham qiymatni, ham turni tekshiradi"}, {"id": "b", "text": "Farqi yo''q"}, {"id": "c", "text": "== qattiqroq tekshiradi"}, {"id": "d", "text": "=== faqat raqamlarni tekshiradi"}]', 'a', 'Qat''iy tenglik operatori === turlarni o''zgartirmay tekshiradi.', 8),
('33333333-3333-3333-3333-333333333333', 'Closure nima?', '[{"id": "a", "text": "Ichki funksiyaning tashqi funksiya o''zgaruvchilarini eslab qolishi"}, {"id": "b", "text": "Siklni to''xtatuvchi buyruq"}, {"id": "c", "text": "Xatolarni yopish usuli"}, {"id": "d", "text": "Dizayn qoidasi"}]', 'a', 'JavaScript da funksiyalar o''zi yaratilgan muhitni yodda saqlaydi.', 9),
('33333333-3333-3333-3333-333333333333', 'Array.map() qachon ishlatiladi?', '[{"id": "a", "text": "Massiv elementlarini o''zgartirib yangi massiv yaratishda"}, {"id": "b", "text": "Faqat filtrlashda"}, {"id": "c", "text": "Elementlarni o''chirishda"}, {"id": "d", "text": "Massiv uzunligini topishda"}]', 'a', 'map barcha elementlarga berilgan funksiyani qo''llab, yangi massiv qaytaradi.', 10);
